# Generated by Django 3.1 on 2023-08-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='account',
            new_name='user',
        ),
    ]
